# docker compose up -d --build --force-recreate
version: '3.8'
name: max

services:

  db-max:
    container_name: max-db-max
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=max
      - POSTGRES_PASSWORD=max
      - POSTGRES_DB=max
    volumes:
      - $VOLUME/postgres/max/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network
  
  discovery:
    build:
      context: ../maxtitanium.discovery
      dockerfile: Dockerfile
    container_name: max-discovery
    image: max-discovery:latest
    ports:
      - 8761:8761
    restart: always
    networks:
      - private-network

  account:
    build:
      context: ../maxtitanium.account-resource
      dockerfile: Dockerfile
    container_name: max-account
    image: max-account:latest
    #ports:
    #  - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://max-db-max:5432/max
      - spring.datasource.username=max
      - spring.datasource.password=max
      - eureka.client.service-url.defaultZone=http://max-discovery:8761/eureka
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-max
      - discovery
    
  auth:
    build:
      context: ../maxtitanium.auth-resource
      dockerfile: Dockerfile
    container_name: max-auth
    image: max-auth:latest
    ports:
      - 8080:8080
    environment:
      - eureka.client.service-url.defaultZone=http://max-discovery:8761/eureka
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - discovery
      - account


networks:
  private-network:
    driver: bridge