# docker compose up -d --build --force-recreate
version: '3.8'
name: max

services:

  db-max:
    container_name: max-db-max
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=max
      - POSTGRES_PASSWORD=max
      - POSTGRES_DB=max
    volumes:
      - $VOLUME/postgres/max/data:/var/lib/postgresql/data
    restart: always
    networks:
      - private-network
  
  account:
    build:
      context: ../maxtitanium.account-resource
      dockerfile: Dockerfile
    image: max-account:latest
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://max-db-max:5432/max
      - spring.datasource.username=max
      - spring.datasource.password=max
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private-network
    depends_on:
      - db-max


networks:
  private-network:
    driver: bridge